scripts: vz-cpt/rst-action.in -- Save and restore memory limits
When we restore container and tight up its memory limits
it must be done in a state when container is restored but
not yet running. For this sake in CRIU we introduce
"post-sigreturn" action. The scripts in the package
do save values in images and restore them back.

https://jira.sw.ru/browse/PSBM-56407

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>

diff --git a/scripts/vz-cpt-action.in b/scripts/vz-cpt-action.in
--- a/scripts/vz-cpt-action.in
+++ b/scripts/vz-cpt-action.in
@@ -31,6 +31,20 @@ fi
 
 set -e
 case "$CRTOOLS_SCRIPT_ACTION" in
+"pre-dump")
+	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
+		echo "Missing parameter CRTOOLS_IMAGE_DIR"
+		exit 1
+	fi
+	if [ -n "$VEID" ]; then
+		cat /sys/fs/cgroup/memory/machine.slice/$VEID/memory.limit_in_bytes > \
+			$CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img || \
+			{ echo "Failed to dump memory limit in bytes"; exit 1; }
+		cat /sys/fs/cgroup/memory/machine.slice/$VEID/memory.memsw.limit_in_bytes > \
+			$CRTOOLS_IMAGE_DIR/vz_memory_memsw_limit_in_bytes.img || \
+			{ echo "Failed to dump memory swap limit in bytes"; exit 1; }
+	fi
+	;;
 "post-dump")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
 		echo "Missing parameter CRTOOLS_IMAGE_DIR"
diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -96,6 +96,22 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 
 	[ "$ret" = "0" ] || { echo "Failed on network unlocking for $VEID"; exit 1; }
 	;;
+"post-sigreturn")
+	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
+		echo "Missing parameter CRTOOLS_IMAGE_DIR"
+		exit 1
+	fi
+	if [ -n "$VEID" ]; then
+		[ -f "$CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img" ] && \
+			{ echo `cat $CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img` > \
+				/sys/fs/cgroup/memory/machine.slice/$VEID/memory.limit_in_bytes || \
+				{ echo "Failed to restore core_pattern"; exit 1; } }
+		[ -f "$CRTOOLS_IMAGE_DIR/vz_memory_memsw_limit_in_bytes.img" ] && \
+			{ echo `cat $CRTOOLS_IMAGE_DIR/vz_memory_memsw_limit_in_bytes.img` > \
+				/sys/fs/cgroup/memory/machine.slice/$VEID/memory.memsw.limit_in_bytes || \
+				{ echo "Failed to restore core_pattern"; exit 1; } }
+	fi
+	;;
 "post-restore")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
 		echo "Missing parameter CRTOOLS_IMAGE_DIR"
