scripts: show hint when vzctl reports an error via WAITFD
Vzctl can report an error via WAITFD this will lead to vz-cpt-action
script fail and thus CRIU fail. Let's print a hint to criu log to make
it easier to understand that actual error is in vzctl.

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

diff --git a/scripts/vz-cpt-action.in b/scripts/vz-cpt-action.in
--- a/scripts/vz-cpt-action.in
+++ b/scripts/vz-cpt-action.in
@@ -127,7 +127,10 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 	[ -n "$STATUSFD" ] && printf '\0\0\0\0' >&${STATUSFD}
 	[ -n "$WAITFD" ] && ret=$(head -c 4 <&$WAITFD | hexdump -e '"%d"' -n 4)
 
-	[ "$ret" = "0" ]
+	if [ "$ret" != "0" ]; then
+		echo "Error reported to criu via WAITFD from vzctl, see vzctl.log"
+		exit 1
+	fi
 	;;
 "dump-alive")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
