vz-cpt/vz-rst: check that required VEID env is provided
We already rely that VEID is set when setup cgroup_root, lets add a
sanity check that it is actually set.

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

diff --git a/scripts/vz-cpt.in b/scripts/vz-cpt.in
--- a/scripts/vz-cpt.in
+++ b/scripts/vz-cpt.in
@@ -30,6 +30,11 @@
 #   VE_PID      - PID of CT init process
 exec 1>&2
 
+if [ -z "$VEID" ]; then
+	echo "Missing parameter VEID"
+	exit 1
+fi
+
 action_script=@SCRIPTDIR@/vz-cpt-action
 props_config=@SCRIPTDIR@/cgroup-props.conf
 dumpdir="$VE_DUMP_DIR".tmp
diff --git a/scripts/vz-rst.in b/scripts/vz-rst.in
--- a/scripts/vz-rst.in
+++ b/scripts/vz-rst.in
@@ -31,6 +31,12 @@
 # Optional parameters:
 #   VE_VETH_DEVS  - pair of veth names (CT=HW\n)
 exec 1>&2
+
+if [ -z "$VEID" ]; then
+	echo "Missing parameter VEID"
+	exit 1
+fi
+
 veth_args=""
 for dev in $VE_VETH_DEVS; do
 	veth_args="$veth_args --veth-pair $dev"
