CT c/r kernel.core_pattern in criu action scripts
We have kernel.core_pattern virtualized per VZCT, that means:
each CT has own sysctl and coredumps are saved relative to VZCT fs
root accoring to that sysctl. Also coredump collector runs in
CTs usermodehelper. We need to c/r these sysctl.

First I tried to do it as criu plugin to save core_pattern in native
criu's protobuf format using pb_read_one pb_write_one, but it turned
out that we can not simply compile in vzct.img protobuf entry for
Virtuozzo's custom properties in CRIU.

On attach to ve/101 cgroup in ve_attach we change task_ve to 101
so it is enouth for sysctl_virtual to work with core_pattern copy
of CT 101.

v2: add vz_ prefix to decrease the chance of images intersection
v3: use cgexec instead of vzctl as this is not good practice to call
vzctl from vzctl hook

https://bugs.openvz.org/browse/OVZ-6696
https://jira.sw.ru/browse/PSBM-44145
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

diff --git a/scripts/vz-cpt-action.in b/scripts/vz-cpt-action.in
--- a/scripts/vz-cpt-action.in
+++ b/scripts/vz-cpt-action.in
@@ -32,6 +32,12 @@ fi
 set -e
 case "$CRTOOLS_SCRIPT_ACTION" in
 "post-dump")
+	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
+		echo "Missing parameter CRTOOLS_IMAGE_DIR"
+		exit 1
+	fi
+	[ -n "$VEID" ] && { cgexec -g ve:$VEID cat /proc/sys/kernel/core_pattern > \
+		$CRTOOLS_IMAGE_DIR/vz_core_pattern.img || { echo "Failed to dump core_pattern"; exit 1; } }
 	ret=0
 	[ -n "$STATUSFD" ] && printf '\0\0\0\0' >&${STATUSFD}
 	[ -n "$WAITFD" ] && ret=$(cat <&$WAITFD | hexdump -e '"%d"' -n 4)
diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -82,4 +82,14 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 
 	[ "$ret" -eq "0" ]
 	;;
+"post-restore")
+	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
+		echo "Missing parameter CRTOOLS_IMAGE_DIR"
+		exit 1
+	fi
+	if [ -f "$CRTOOLS_IMAGE_DIR/vz_core_pattern.img" ]; then
+		[ -n "$VEID" ] && { cgexec -g ve:$VEID echo `cat $CRTOOLS_IMAGE_DIR/vz_core_pattern.img` \
+			> /proc/sys/kernel/core_pattern || { echo "Failed to restore core_pattern"; exit 1; } }
+	fi
+	;;
 esac
