uptime_grow test detects that time's gone backward for ~0.5sec #PSBM-128522
we currently dump the ve.clock_bootbased and the ve.clock_monotonic inconsistently,
we dump them from the vz-cpt script before calling criu.

The fix is dump ve.clock_* on frozen CT

Signed-off-by: Igor Sukhih <igor@virtuozzo.com>

diff --git a/scripts/vz-cpt-action.in b/scripts/vz-cpt-action.in
--- a/scripts/vz-cpt-action.in
+++ b/scripts/vz-cpt-action.in
@@ -40,6 +40,11 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 		exit 1
 	fi
 	if [ -n "$VEID" ]; then
+		# Save monotonic offsets for next restore
+		cat /sys/fs/cgroup/ve/$VEID/ve.clock_bootbased  > $CRTOOLS_IMAGE_DIR/vz_clock_bootbased.img || \
+			{ echo "Failed to dump ve.clock_bootbased"; exit 1;  }
+		cat /sys/fs/cgroup/ve/$VEID/ve.clock_monotonic  > $CRTOOLS_IMAGE_DIR/vz_clock_monotonic.img || \
+			{ echo "Failed to dump ve.clock_monotonic"; exit 1; }
 		cat /sys/fs/cgroup/memory/machine.slice/$VEID/memory.limit_in_bytes > \
 			$CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img || \
 			{ echo "Failed to dump memory limit in bytes"; exit 1; }
