scripts/nfs-server: also stop nfsdcld service along with nfs-server
The nfsdcld puts an inotify on rpc_pipefs, and it lacks migration
support (file handle support), so we need to stop it along with
nfs-server to suspend.

https://jira.sw.ru/browse/PSBM-140145

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

diff --git a/scripts/vz-cpt-action.in b/scripts/vz-cpt-action.in
--- a/scripts/vz-cpt-action.in
+++ b/scripts/vz-cpt-action.in
@@ -70,6 +70,11 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 				# This explicitly waits for rpc.mountd process exit
 				$TIMEOUT $NFSD_TIMEOUT $JOIN_CT $SYSTEMCTL stop nfs-mountd || \
 					{ echo "Failed to stop nfs-mountd"; exit 1; }
+				# This explicitly stops nfsdcld service
+				if $TIMEOUT $NFSD_TIMEOUT $JOIN_CT $SYSTEMCTL is-active nfsdcld; then
+					$TIMEOUT $NFSD_TIMEOUT $JOIN_CT $SYSTEMCTL stop nfsdcld || \
+						{ echo "Failed to stop nfsdcld"; exit 1; }
+				fi
 				echo "Stopped nfs-server service"
 			else
 				echo 0 > $CRTOOLS_IMAGE_DIR/vz_nfsd_active.img || \
