vzerror: rederect error message to stderr
Signed-off-by: Igor Sukhih <igor@parallels.com>

diff --git a/scripts/vz-functions.in b/scripts/vz-functions.in
--- a/scripts/vz-functions.in
+++ b/scripts/vz-functions.in
@@ -79,7 +79,7 @@ function vzerror()
 {
 	# print errors to stdout too
 	ERR=$?
-	echo "$SELFNAME ERROR: $1"
+	echo "$SELFNAME ERROR: $1" >&2
 	exit $2
 }
 
