Rework setting up memory limits on restore
Currenlty we restore memory limits in post-resume
stage where applications are already executing
after restore stage which in worst scenario may
cause container to stop restoration procedure.

Instead lets use another strategy:

 - start restore with ram limited but unlimited swap
 - on post-restore stage setup swap limit back
 - kick containers to run

https://jira.sw.ru/browse/PSBM-58742

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>

diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -96,22 +96,6 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 
 	[ "$ret" = "0" ] || { echo "Failed on network unlocking for $VEID"; exit 1; }
 	;;
-"post-sigreturn")
-	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
-		echo "Missing parameter CRTOOLS_IMAGE_DIR"
-		exit 1
-	fi
-	if [ -n "$VEID" ]; then
-		[ -f "$CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img" ] && \
-			{ echo `cat $CRTOOLS_IMAGE_DIR/vz_memory_limit_in_bytes.img` > \
-				/sys/fs/cgroup/memory/machine.slice/$VEID/memory.limit_in_bytes || \
-				{ echo "Failed to restore memory.limit_in_bytes"; exit 1; } }
-		[ -f "$CRTOOLS_IMAGE_DIR/vz_memory_memsw_limit_in_bytes.img" ] && \
-			{ echo `cat $CRTOOLS_IMAGE_DIR/vz_memory_memsw_limit_in_bytes.img` > \
-				/sys/fs/cgroup/memory/machine.slice/$VEID/memory.memsw.limit_in_bytes || \
-				{ echo "Failed to restore memory.memsw.limit_in_bytes"; exit 1; } }
-	fi
-	;;
 "post-restore")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
 		echo "Missing parameter CRTOOLS_IMAGE_DIR"
@@ -132,10 +116,11 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 			 > /proc/sys/kernel/randomize_va_space || { echo "Failed to restore randomize_va_space"; exit 1; } }
 	fi
 	[ -n "$VEID" ] && { cgset -r ve.pseudosuper="0" $VEID || { echo "Failed to drop pseudosuper on $VEID"; exit 1; } }
-	;;
-"post-resume")
+	ret=0
 	[ -n "$STATUSFD" ] && printf '\0\0\0\0' >&${STATUSFD}
 	[ -n "$WAITFD" ] && ret=$(head -c 4 <&$WAITFD | hexdump -e '"%d"' -n 4)
+
+	[ "$ret" = "0" ] || { echo "Failed on post-restore for $VEID"; exit 1; }
 	;;
 esac
 
