vz-rst-action: Drop pseudosuper on pre-resume stage
We need to operate with pseudosuper rights to unlock
network for sockets restore sake. This problem is
a side effect of fixing bug

https://jira.sw.ru/browse/PSBM-98702

Which required by the kernel commit
1a31e40d3ee732c86f8961506291039267fff26f

https://jira.sw.ru/browse/PSBM-98881
https://jira.sw.ru/browse/PSBM-98915

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>
Reviewed-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Signed-off-by: Igor Sukhih <igor@virtuozzo.com>

diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -101,6 +101,14 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 		[ -n "$VE_PID_MAX" ] && cgset -r ve.pid_max="$VE_PID_MAX" $VEID
 	fi
 	;;
+"pre-resume")
+	#
+	# We drop pseudosuper on pre-resume stage since we need to run
+	# iptable helpers inside container during sockets restore. Note
+	# the containers are still in stopped stage, CRIU will kick them
+	# up to run via freezer after this stage.
+	[ -n "$VEID" ] && { cgset -r ve.pseudosuper="0" $VEID || { echo "Failed to drop pseudosuper on $VEID"; exit 1; } }
+	;;
 "post-restore")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
 		echo "Missing parameter CRTOOLS_IMAGE_DIR"
@@ -121,7 +129,6 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 			{ cgexec -g ve:$VEID echo `cat $CRTOOLS_IMAGE_DIR/vz_randomize_va_space.img` \
 			 > /proc/sys/kernel/randomize_va_space || { echo "Failed to restore randomize_va_space"; exit 1; } }
 	fi
-	[ -n "$VEID" ] && { cgset -r ve.pseudosuper="0" $VEID || { echo "Failed to drop pseudosuper on $VEID"; exit 1; } }
 
 	ret=0
 	[ -n "$CRIU_ACTION_POST_RESUME_READ_FD" ] && printf '\0\0\0\0' >&${CRIU_ACTION_POST_RESUME_READ_FD}
