scripts: add support of nfs-server migration
Criu can't dump nfs server, for instance:

- nfsd/rpcpipefs contents is not restored
- opened /proc/<pid>/net/rpc/auth.unix.ip/channel is not restored

This is a workaround to support nfs server migration. Idea is to stop
nfs server before suspending container and restart it after resuming it.
As nfs server is stateless, after restart all nfs clients of this server
would reconect flawlessly, so it should not be much difference between
this w/a and honest migration.

Add timeout for operations with services as if a container is "pause"d
or "snapshot"ed by vzctl or in case container user freezes container
processes we can't stop nfs server, thus just skip this and fail later
as criu would not be able to handle running nfs server. Consider this
yet unsupported.

https://jira.sw.ru/browse/PSBM-138439

Co-Developed-by: Yuriy Vasiliev <yuriy.vasiliev@virtuozzo.com>
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -31,6 +31,13 @@ exec 1>&2
 
 action_script=@SCRIPTDIR@/vz-rst-action
 
+VZCTL="/usr/sbin/vzctl"
+JOIN_CT="$VZCTL --skiplock --skipowner exec3 $VEID"
+SYSTEMCTL="/bin/systemctl -q"
+VE_FEATURE_NFSD=$(( 1 << 8 ))
+TIMEOUT="/usr/bin/timeout"
+NFSD_TIMEOUT="10s"
+
 update_devices()
 {
 	local olddev=$1
@@ -169,6 +176,15 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 	[ -n "$STATUSFD" ] && printf '\0\0\0\0' >&${STATUSFD}
 	[ -n "$WAITFD" ] && ret=$(head -c 4 <&$WAITFD | hexdump -e '"%d"' -n 4)
 	[ "$ret" = "0" ] || { echo "Failed on post-restore for $VEID"; exit 1; }
+	;;
+"post-resume")
+	# For container with nfsd feature restart nfs-server if it was stopped before dump
+	if [ -n "$VEID" ] && [ -n "$VE_FEATURES" ] && (( $VE_FEATURES & $VE_FEATURE_NFSD )) && \
+		[ -n "$VZ_NFSD_ACTIVE" ] && [ "$VZ_NFSD_ACTIVE" = "1" ]; then
+		$TIMEOUT $NFSD_TIMEOUT $JOIN_CT $SYSTEMCTL start nfs-server || \
+			{ echo "Failed to start nfs-server"; exit 1; }
+		echo "Restarted nfs-server service"
+	fi
 	;;
 esac
 
