vz-rst-action: line 97: [: : integer expression expected #PSBM-52916
The $ret could be empty if no result, the fix is use string compare

ret=$(cat <&$WAITFD | hexdump -e '"%d"' -n 4)
- [ "$ret" -eq "0" ]
+ [ "$ret" != "0" ]

Signed-off-by: Igor Sukhih <igor@virtuozzo.com>

diff --git a/scripts/vz-rst-action.in b/scripts/vz-rst-action.in
--- a/scripts/vz-rst-action.in
+++ b/scripts/vz-rst-action.in
@@ -94,7 +94,7 @@ case "$CRTOOLS_SCRIPT_ACTION" in
 	[ -n "$STATUSFD" ] && printf '\0\0\0\0' >&${STATUSFD}
 	[ -n "$WAITFD" ] && ret=$(cat <&$WAITFD | hexdump -e '"%d"' -n 4)
 
-	[ "$ret" -eq "0" ] || { echo "Failed on network unlocking for $VEID"; exit 1; }
+	[ "$ret" != "0" ] || { echo "Failed on network unlocking for $VEID"; exit 1; }
 	;;
 "post-restore")
 	if [ -z "$CRTOOLS_IMAGE_DIR" ]; then
