Refactor veid variable assignments. Remove else case for vznetcfg script

diff --git a/scripts/vznetcfg.in b/scripts/vznetcfg.in
--- a/scripts/vznetcfg.in
+++ b/scripts/vznetcfg.in
@@ -84,27 +84,25 @@ delif()
 if [ -n "$EXTERNAL_SCRIPT" -a -x "$EXTERNAL_SCRIPT" ]; then
         export VEID
         exec "$EXTERNAL_SCRIPT" $@
-else
-
-	case "$1" in
-		addif)
-			if test $# -ne 3; then
-				usage
-				exit 1
-			fi
-
-			delif "$2"
-			addif "$2" "$3"
-		;;
-		delif)
-			delif "$2"
-		;;
-		*)
-			echo "invalid action"
-			exit 1
-		;;
-	esac
-
 fi
+
+case "$1" in
+	addif)
+		if test $# -ne 3; then
+			usage
+			exit 1
+		fi
+
+		delif "$2"
+		addif "$2" "$3"
+	;;
+	delif)
+		delif "$2"
+	;;
+	*)
+		echo "invalid action"
+		exit 1
+	;;
+esac
 
 exit 0
