vznetcfg: Use vnetwork as bridge name if bound is iface empty, #PSBM-34812
Special case for OpenStack.
if 'prlsrvctl net info $NETWORK' return empty "Bound to:"
treat provided natwork name as bridge name

Signed-off-by: Igor Sukhih <igor@parallels.com>

diff --git a/scripts/vznetcfg.in b/scripts/vznetcfg.in
--- a/scripts/vznetcfg.in
+++ b/scripts/vznetcfg.in
@@ -36,11 +36,14 @@ addif()
 	fi 
 
 	bound_iface=`echo "$bound_iface" | awk '/Bound To:/{print $3}'`
-
-	br=`brctl show | awk '/'$bound_iface'$/{print $1}'`
-	if [ -z "$br" ]; then
-		echo "Unable to find bridge by bounded iface $bound_iface"
-		exit 1
+	if [ -n "$bound_iface" ]; then
+		br=`brctl show | awk '/'$bound_iface'$/{print $1}'`
+		if [ -z "$br" ]; then
+			echo "Unable to find bridge by bounded iface $bound_iface"
+			exit 1
+		fi
+	else
+		br="$2"
 	fi
 
 	brctl addif $br $iface
